config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root 'eatings#index'

  get 'about', to: 'pages#about'

  resources :eatings, only: [:new, :create, :index, :edit, :update, :destroy]

  devise_for :users
end

app/models/eating.rb
class Eating < ActiveRecord::Base
  scope :by_date, -> { order('created_at ASC') }

  before_save do
    self.food = food[0].split(',').map { |food_entry| food_entry.mb_chars.strip.capitalize.to_s }
  end

  belongs_to :user

  def day
    I18n.l(created_at, format: '%d %B')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :validatable

  has_many :eatings

  validates :email, :encrypted_password, :telegram_id, presence: true
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      redirect_to root_path if !current_user || current_user.email != ENV['ADMIN_EMAIL']
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/eatings_controller.rb
module Admin
  class EatingsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Eating.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Eating.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :set_timezone

  def set_timezone
    min = request.cookies["timezone"].to_i
    Time.zone = ActiveSupport::TimeZone[-min.minutes]
  end
end

app/controllers/eatings_controller.rb
class EatingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @eatings = current_user.eatings.by_date
  end

  def edit
    @eating = Eating.find(params[:id])
  end

  def new
    @eating = Eating.new
  end

  def create
    Eating.create(eating_attributes.merge(user: current_user))

    redirect_to(root_path)
  end

  def update
    @eating = Eating.find(params[:id])

    @eating.update_attributes(eating_attributes)

    redirect_to(root_path)
  end

  def destroy
    @eating = Eating.find(params[:id])

    @eating.destroy

    redirect_to(root_path)
  end

  private

  def eating_attributes
    params.require(:eating).permit(:created_at, food: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about; end
  def feedback; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def card_color(eatings)
    case eatings.count
    when 5 then 'green'
    when 1..2 then 'red'
    when 3..4 then 'yellow'
    end
  end

  def eat_grade(eatings)
    case eatings.count
    when 5 then 'отлично'
    when 1..2 then 'плохо'
    when 3..4 then 'так себе'
    end
  end
end

app/views/eatings/edit.slim
.row.centered
  = form_for @eating, html: { class: "ui form" } do |f|
    .field
      = text_field_tag 'eating[food][]', @eating.food.join(','), autofocus: true, placeholder: 'Еда'
    .field
      = f.text_field :created_at, value: @eating.created_at
    = f.submit "Сохранить", class: "ui basic button green"
    = link_to "Назад", root_path, class: "ui basic button grey"
    = link_to "Удалить", eating_path(@eating), method: :delete, class: "ui basic button red"

app/views/eatings/index.slim
.ui.row.centered
  .ui.divided.grid.centered
    .ui.feed
      - @eatings.group_by(&:day).each do |day, eatings|
        .event
          .label.ui.basic class="#{card_color(eatings)}"
            .ui.header.small
              = day
            .ui.sub.header
              = l(eatings[0].created_at, format: "%A")

          .content
            .summary
              .ui.feed
                - eatings.each do |eating|
                  .event.dimmable
                    .ui.dimmer
                      .content
                        .center
                          = link_to edit_eating_path(eating), class: 'ui icon' do
                            i.icon.edit.big.black.popup data-content='Редактировать'
                          = link_to eating_path(eating), method: :delete, class: 'ui icon' do
                            i.icon.remove.big.black.popup data-content='Удалить'
                    .content
                      .summary
                        .date>
                          = l(eating.created_at, format: :time)
                        - eating.food.each do |food|
                          .ui.label.basic= food

        .ui.divider &nbsp;

app/views/eatings/new.slim
.ui.row.centered
  = form_for @eating, html: { class: "ui form" } do |f|
    .field
      = text_field_tag 'eating[food][]', @eating.food, autofocus: true, placeholder: 'Что съел?'
    .centered
      = f.submit "Сохранить", class: "ui basic button green"
      = link_to "Назад", root_path, class: "ui basic button gray"

app/views/layouts/application.slim
doctype html
html
  head
    title
      | Eatontime
    link[href="https://fonts.googleapis.com/css?family=Open+Sans:300&subset=latin,cyrillic" rel="stylesheet" type="text/css"]
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .ui.grid.container
      .ui.row.centered

      .row.centered.four.column
        .ui.secondary.pointing.menu
          = link_to 'Мама, я поел', root_path, class: "item icon popup #{'active' if !user_signed_in? || current_page?(controller: 'eatings', action: 'index')}", data: { content: 'Главная' }
          - if user_signed_in?
            = link_to new_eating_path, class: "item  icon popup #{'active' if user_signed_in? && current_page?(controller: 'eatings', action: 'new')}", data: { content: 'Покушал сегодня?' } do
              i.icon.comment.plus
            .right.menu
              = link_to about_path, class: "item icon popup #{'active' if current_page?(controller: 'pages', action: 'about')}",
                data: { content: 'Что происходит?' } do
                  i.icon.help
              = link_to destroy_user_session_path, method: :delete, class: "item icon popup", data: { content: 'Выход' } do
                i.icon.power

      = yield

      .ui.row.centered
        = link_to root_path do
          = image_tag("cat.jpg", width: 300, height: 169)
      .ui.row.centered

    script
      |  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','//www.google-analytics.com/analytics.js','ga'); ga('create', '<ruby code="= ENV["GA_TRACKNG_CODE"]"></ruby>', 'auto'); ga('send', 'pageview');

app/views/pages/about.slim
.ui.row.centered
  .segment
    p
      | Пользоваться можно либо через веб-версию (вы уже здесь), либо с помощью <a href="#{ENV['TELEGRAM_BOT_LINK']}">бота в Telegram</a>.
    p
      | Если съели несколько блюд за раз – их можно перечислить через запятую.


.ui.row.centered
  .ui.header.medium Обратная связь
.ui.row.centered

  form.ui.form accept-charset="UTF-8" action="#{ENV['FORMKEEP_URL']}" method="POST"
    input type="hidden" name="utf8" value="✓"
    .ui.field
      input type="text" name="name" placeholder="Имя"
    .ui.field
      textarea cols="50" type="textarea" name="message" placeholder="Что можно улучшить?"
    button.ui.button.basic type="submit" Отправить